/*
** EPITECH PROJECT, 2021
** libC - Starter
** File description:
** This file was automatically generated by libC starter command.
*/

#include "../include/defender.h"

int pre_init(int ac, char **av)
{
    if (ac != 2 )
        return (my_error("Error: Type ./defender -h for help.", 84));
    if (check_args(av, 1, "-h"))
        return (my_error(HELP_MESSAGE, 84));
    if (my_strlen(av[1]) > 20)
        return (my_error("Error: Type ./defender -h for help.", 84));
    return (0);
}

int main(int ac, char **av)
{
    game_t game;

    if (pre_init(ac, av) == 84)
        return (84);
    load_assets(&game);
    init_windows(&game);
    void (*game_ptr[7])(game_t *) = {&loop_menu, 0, 0, 0, 0, 0, 0};
    while (sfRenderWindow_isOpen(game.window)) {
         (*game_ptr[game.state])(&game);
    }
    return 0;
}